[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
pyth_contract = "42249qzKKgXW7MYno4xXMo9ryqzYo1jSUzFt3D4hgofe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
